### ISSUE TITLE
Misión Perturbar sus refuerzos

### ISSUE THREAD

**Issue by exanime159147** [athenaswow/BugTracker-Athenas-WoW-3.3.5a#2]
Rethor
Al momento de usar el item para detonar los portales, en el último segundo para completarse se cancela y me dice no tienes objetivo, por lo que no me deja hacer la misión

**Comment by DennisCalderon** [comment]
actualmente existen 2 misiones con el mismo nombre, a cual te refieres?
si es posible sube una foto de tu personaje con el mensaje de error.
