### ISSUE TITLE
Misión La vinculadora terrestre

### ISSUE THREAD

**Issue by exanime159147** [athenaswow/BugTracker-Athenas-WoW-3.3.5a#3]
Rethor
La misiín dice que hablar con la vinculadora, sin embargo no le aparece el signo de interrogación para hablar con ella y seguir con la cadena de msiones

**Comment by exanime159147** [comment]
Peninsula de fuego infernal

**Comment by DennisCalderon** [comment]
mañana lo reviso, por favor en el futuro trata de agregar algo mas de información.

**Comment by DennisCalderon** [comment]
![image](https://user-images.githubusercontent.com/43972855/81875831-d4e13600-9546-11ea-95d0-821016a89a7e.png)
Ya revise los requisitos de la misión y todo parece funcionar bien por favor sube los datos de tu personaje: clase, raza y nivel.

si no obtengo respuesta en los próximos 5 cerraré el reporte
